# Generated by Django 5.1.4 on 2025-05-15 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='officials.league'),
        ),
        migrations.AddField(
            model_name='meet',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meets', to='officials.league'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='meet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='officials.meet'),
        ),
        migrations.AddField(
            model_name='official',
            name='certification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officials', to='officials.certification'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='officials.official'),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='officials.division'),
        ),
        migrations.AddField(
            model_name='official',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='officials', to='officials.team'),
        ),
        migrations.AddField(
            model_name='meet',
            name='host_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meets', to='officials.team'),
        ),
        migrations.AddField(
            model_name='meet',
            name='participating_teams',
            field=models.ManyToManyField(related_name='meets', to='officials.team'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('meet', 'official', 'role')},
        ),
    ]
