# Generated by Django 5.2.1 on 2025-05-15 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='teams',
        ),
        migrations.AddField(
            model_name='official',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='officials.team'),
        ),
    ]
