# Generated by Django 5.2.1 on 2025-05-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0003_remove_official_teams_official_team'),
    ]

    operations = [
        # Step 1: Add the new name field
        migrations.AddField(
            model_name='official',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        # Step 2: Populate the name field with first_name + last_name
        migrations.RunSQL(
            "UPDATE officials_official SET name = CONCAT(first_name, ' ', last_name);",
            "UPDATE officials_official SET first_name = name, last_name = '';"
        ),
        # Step 3: Remove the first_name and last_name fields
        migrations.RemoveField(
            model_name='official',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='official',
            name='last_name',
        ),
        # Step 4: Make email optional
        migrations.AlterField(
            model_name='official',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        # Step 5: Remove years_experience field
        migrations.RemoveField(
            model_name='official',
            name='years_experience',
        ),
        # Step 6: Add proficiency field
        migrations.AddField(
            model_name='official',
            name='proficiency',
            field=models.CharField(
                choices=[('Provisional', 'Provisional'), ('Beginner', 'Beginner'), 
                        ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), 
                        ('Expert', 'Expert')],
                default='Beginner',
                max_length=20,
            ),
        ),
    ]
