# Generated by Django 5.2.1 on 2025-05-15 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0005_auto_20250515_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mascot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='official',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='officials.team'),
            preserve_default=False,
        ),
    ]
