# Generated by Django 5.2.1 on 2025-05-15 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0006_team_mascot_alter_official_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('length', models.PositiveSmallIntegerField(default=50, help_text='Pool length')),
                ('units', models.CharField(choices=[('Yards', 'Yards'), ('Meters', 'Meters')], default='Yards', max_length=6)),
                ('lanes', models.PositiveSmallIntegerField(default=6, help_text='Number of lanes')),
                ('bidirectional', models.BooleanField(default=False, help_text='Can races be run in both directions simultaneously?')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='officials.team')),
            ],
        ),
    ]
