# Generated by Django 5.2.1 on 2025-05-15 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0008_remove_meet_description_remove_meet_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='end_time',
        ),
        migrations.AddField(
            model_name='meet',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meets', to='officials.pool'),
        ),
        migrations.AddField(
            model_name='meet',
            name='weather_forecast',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
