# Generated by Django 5.2.1 on 2025-05-16 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0010_team_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeagueAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_admins', to='officials.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_admin_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'League Admin',
                'verbose_name_plural': 'League Admins',
                'unique_together': {('user', 'league')},
            },
        ),
    ]
