# Generated by Django 5.2.1 on 2025-05-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0011_userleagueadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('meet_type', models.CharField(choices=[('regular', 'Regular Season'), ('playoff', 'Playoff'), ('championship', 'Championship'), ('tournament', 'Tournament'), ('special', 'Special Event'), ('other', 'Other')], default='regular', max_length=20)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('participant_count', models.IntegerField(default=1)),
                ('officials_required', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meet',
            name='meet_type',
            field=models.CharField(choices=[('regular', 'Regular Season'), ('playoff', 'Playoff'), ('championship', 'Championship'), ('tournament', 'Tournament'), ('special', 'Special Event'), ('other', 'Other')], default='regular', max_length=20),
        ),
    ]
