# Generated by Django 5.2.1 on 2025-05-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0013_remove_event_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
