# Generated by Django 5.2.1 on 2025-05-28 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0014_event_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_number', 'meet_type']},
        ),
        migrations.AddField(
            model_name='event',
            name='event_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Event number between 1-99', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_number', 'meet_type')},
        ),
    ]
