# Generated by Django programmatically

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0015_alter_event_options_event_event_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
