# Generated by Django 5.2.1 on 2025-05-29 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0002_strategy'),
        ('officials', '0016_alter_event_description'),
    ]

    operations = [
    ]
