# Generated by Django 5.2.1 on 2025-05-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0017_merge_0002_strategy_0016_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='desc'),
            preserve_default=False,
        ),
    ]
