# Generated by Django 5.2.1 on 2025-06-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0018_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='The name or title of the position (e.g., Referee, Head Linesman, Side Judge)', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Typical on-field location or area of responsibility for this position (e.g., Backfield, Sideline, Deep Wing)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(help_text='The officiating strategy this position belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='officials.strategy')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['strategy', 'role'],
                'unique_together': {('role', 'strategy')},
            },
        ),
    ]
