# Generated by Django 5.2.1 on 2025-06-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0019_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleagueadmin',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=10),
        ),
    ]
