# Generated by Django 5.2.1 on 2025-06-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0020_userleagueadmin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='meet_type',
            field=models.CharField(choices=[('dual', 'Dual'), ('divisional', 'Divisional'), ('invitational', 'Invitational')], default='dual', max_length=20),
        ),
    ]
