# Generated by Django 5.2.1 on 2025-06-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0021_update_meet_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='position',
            name='location',
            field=models.CharField(help_text='Typical on-field location or area of responsibility for this position (e.g., Backfield, Sideline, Deep Wing)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('role', 'strategy', 'location')},
        ),
    ]
