# Generated by Django 5.2.1 on 2025-06-09 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0023_fix_position_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Indicates if this position is mandatory for the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='Event that requires this position', on_delete=django.db.models.deletion.CASCADE, related_name='event_positions', to='officials.event')),
                ('position', models.ForeignKey(help_text='Position required for this event', on_delete=django.db.models.deletion.CASCADE, related_name='event_positions', to='officials.position')),
            ],
            options={
                'verbose_name': 'Event Position',
                'verbose_name_plural': 'Event Positions',
                'ordering': ['event', 'position'],
                'unique_together': {('event', 'position')},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='events',
            field=models.ManyToManyField(related_name='positions', through='officials.EventPosition', to='officials.event'),
        ),
    ]
