# Generated by Django 5.2.1 on 2025-06-10 04:14

from django.db import migrations


def set_default_minimum_certification(apps, schema_editor):
    """Set the default minimum certification level to 3 for all existing positions."""
    Position = apps.get_model('officials', 'Position')
    Certification = apps.get_model('officials', 'Certification')
    
    # Try to get a certification with level 3
    level_3_cert = Certification.objects.filter(level=3).first()
    
    # If no level 3 certification exists, create one
    if not level_3_cert:
        level_3_cert = Certification.objects.create(
            name="Level 3",
            abbreviation="L3",
            description="Default certification level required for positions",
            level=3
        )
    
    # Update all positions to use this certification
    Position.objects.all().update(minimum_certification=level_3_cert)


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0025_position_minimum_certification'),
    ]

    operations = [
        migrations.RunPython(set_default_minimum_certification, migrations.RunPython.noop),
    ]
