# Generated by Django 5.2.1 on 2025-06-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0026_set_default_minimum_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the strategy', null=True),
        ),
    ]
