# Generated by Django 5.2.1 on 2025-08-17 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0028_meet_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
    ]
