# Generated by Django 5.2.1 on 2025-08-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0029_meet_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meets', to='officials.strategy'),
        ),
    ]
