# Generated by Django 5.2.1 on 2025-08-18 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0030_meet_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('build_option', models.CharField(choices=[('LIGHTEST', 'Lightest'), ('HEAVIEST', 'Heaviest')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='officials.meet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
